### ISSUE TITLE
Docker-compose config

### ISSUE THREAD

**Issue by rah66** [kadrim/proxy4plex#16]
Thank you for build Linux/ARM64 OS image! I create and use docker-compose (portainer-stack) config:

```
version: "3"
services:
  proxy4plex:
    image: kadrim/proxy4plex
    container_name: proxy4plex
    ports:
      - 80:80
      - 3000:3000
    restart: unless-stopped

```

all working fine! can be added to instructions https://hub.docker.com/r/kadrim/proxy4plex
